WebFont.load({
    google: {
        families: [
            "Source Sans 3:300,400,400i,600,700",
            "Libre Bodoni",
            "Cormorant Garamond",
            "Amatic SC",
            "Bangers",
            "Creepster",
            "Denk One",
            "Fondamento",
            "Grenze Gotisch",
            "Indie Flower",
            "Josefin Sans",
            "Jura",
            "Kalam",
            "Luckiest Guy",
            "Merriweather",
            "Michroma",
            "Nunito",
            "Oswald",
            "Patrick Hand",
            "Permanent Marker",
            "Roboto",
            "Roboto Condensed",
            "Roboto Mono",
            "Sarpanch",
            "Special Elite",
            "Titillium Web",
            "Ubuntu",
        ],
    },
});